### ISSUE TITLE
Seemingly identical buffer throws 'Unrecognized compressed buffer'

### ISSUE THREAD

**Issue by reimund** [nfrechette/acl-js#25]
I'm storing a compressed buffer in a bson document using `new Binary(Buffer.from(compressedTracks._array))`.

But when I'm reading it back in `new ACL.CompressedTracks(buffer, null);` gives me `'Unrecognized compressed buffer'`.

I've written `compressed._array` to a file and then used `diff` to compare it to the deserialized bson buffer and they look identical. Not sure how one of them can work but not the other.

As I do not fully understand the checks in the `ACL.CompressedTracks` constructor I am a bit stuck. Any idea why my buffer is invalid?

**Comment by reimund** [comment]
I figured it out. For some reason I had to convert the buffer to an Uint8Array. Like so:

```javascript
// Put compressed data into bson as a binary field and store it somewhere.
const bson = serialize({ foo: new Binary(Buffer.from(compressed._array.buffer)) });

// Read bson and prepare it for decoding.
const data = deserialize(bson);
const buf = data.foo.buffer;

// Binary.buffer is not compatible with CompressedTracks, but converting it to Uint8Array works.
const a = new Uint8Array(buf.length);
for (let i = 0; i < buf.length; i++) {
    a[i] = buf[i];
}

const compressedTracks = new ACL.CompressedTracks(a);
```

**Comment by nfrechette** [comment]
That's correct, in order to create an instance of a CompressedTracks, you must use either an Uint8Array or an ArrayBuffer. It must also point to the start of the compressed buffer.

I'm not sure what the `Binary` type does but I imagine it didn't line up with the start of the data for some reason. If you think the API could be improved on, feel free to let me know or to submit a PR 👍
